services:
  voice_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345/udp"
      - "8080:8080/tcp"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENVIRONMENT=development
    restart: always